led_strip:
  enable:
    - if: SOC_RMT_SUPPORTED == 1 and ((IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 1) or (IDF_VERSION_MAJOR > 5)) # Used Clock_source_t type was introduced since IDF V5.1
    
esp_delta_ota:
  enable:
    - if: IDF_VERSION_MAJOR > 4
      reason: Example uses esp_app_format component which was introduced in IDF v5.0
  disable:
    - if: SOC_WIFI_SUPPORTED != 1
      reason: Relevant only for WiFi enabled targets
